module IPANumberConstantsSpec where

import Control.Monad (unless)

import IPAConstants.IPANumbers

-- See The International Phonetic Alphabet Number Chart at https://www.internationalphoneticassociation.org/sites/default/files/IPA_Number_chart_(C)2005.pdf

ipaNumbersSpec :: IO ()
ipaNumbersSpec =
	putStrLn "IPA Numbers for IPA characters (and diacritics)"
	>> unless (latin_small_letter_p  ==  101) (error "latin small letter p should be IPA Number 101")
	>> unless (latin_small_letter_b  ==  102) (error "latin small letter b should be IPA Number 102")
	>> unless (latin_small_letter_t  ==  103) (error "latin small letter t should be IPA Number 103")
	>> unless (latin_small_letter_d  ==  104) (error "latin small letter d should be IPA Number 104")
	>> unless (latin_small_letter_t_with_retroflex_hook  ==  105) (error "latin small letter t with retroflex hook should be IPA Number 105")
	>> unless (latin_small_letter_d_with_tail  ==  106) (error "latin small letter d with tail should be IPA Number 106")
	>> unless (latin_small_letter_c  ==  107) (error "latin small letter c should be IPA Number 107")
	>> unless (latin_small_letter_dotless_j_with_stroke  ==  108) (error "latin small dotless j with stroke should be IPA Number 108")
	>> unless (latin_small_letter_k  ==  109) (error "latin small letter k should be IPA Number 109")
	>> unless (latin_small_letter_g  ==  110) (error "latin small letter g should be IPA Number 110")
	>> unless (latin_small_letter_q  ==  111) (error "latin small letter q should be IPA Number 111")
	>> unless (latin_letter_small_capital_g  ==  112) (error "latin letter small capital g should be IPA Number 112")
	>> unless (latin_letter_glottal_stop  ==  113) (error "latin letter glottal stop should be IPA Number 113")
	>> unless (latin_small_letter_m  ==  114) (error "latin small letter m should be IPA Number 114")
	>> unless (latin_small_letter_m_with_hook  ==  115) (error "latin small letter m with hook should be IPA Number 115")
	>> unless (latin_small_letter_n  ==  116) (error "latin small letter n should be IPA Number 116")
	>> unless (latin_small_letter_n_with_retroflex_hook  ==  117) (error "latin small letter n with retroflex hook should be IPA Number 117")
	>> unless (latin_small_letter_n_with_left_hook  ==  118) (error "latin small letter n with left hook should be IPA Number 118")

	>> unless (latin_small_letter_eng  ==  119) (error "latin small letter eng should be IPA Number 119")
	>> unless (latin_letter_small_capital_n  ==  120) (error "latin letter small capital n should be IPA Number 120")
	>> unless (latin_letter_small_capital_b  ==  121) (error "latin letter small capital b should be IPA Number 121")
	>> unless (latin_small_letter_r  ==  122) (error "latin small letter r should be IPA Number 122")
	>> unless (latin_letter_small_capital_r  ==  123) (error "latin letter small capital r should be IPA Number 123")
	>> unless (latin_small_letter_v_with_right_hook  ==  184) (error "latin small letter v with right hook should be IPA Number 184")
	>> unless (latin_small_letter_r_with_fishhook  ==  124) (error "latin small letter r with fishhook should be IPA Number 124")
	>> unless (latin_small_letter_r_with_tail  ==  125) (error "latin small letter r with tail should be IPA Number 125")
	>> unless (latin_small_letter_phi  ==  126) (error "latin small letter phi should be IPA Number 126")
	>> unless (greek_small_letter_beta  ==  127) (error "greek small letter beta should be IPA Number 127")
	>> unless (latin_small_letter_f  ==  128) (error "latin small letter f should be IPA Number 128")
	>> unless (latin_small_letter_v  ==  129) (error "latin small letter v should be IPA Number 129")
	>> unless (greek_small_letter_theta  ==  130) (error "greek small letter theta should be IPA Number 130")
	>> unless (latin_small_letter_eth  ==  131) (error "latin small letter eth should be IPA Number 131")
	>> unless (latin_small_letter_s  ==  132) (error "latin small letter s should be IPA Number 132")
	>> unless (latin_small_letter_z  ==  133) (error "latin small letter z should be IPA Number 133")
	>> unless (latin_small_letter_esh  ==  134) (error "latin small letter esh should be IPA Number 134")
	>> unless (latin_small_letter_ezh  ==  135) (error "latin small letter ezh should be IPA Number 135")
	>> unless (latin_small_letter_s_with_hook  ==  136) (error "latin small letter s with hook should be IPA Number 136")
	>> unless (latin_small_letter_z_with_retroflex_hook  ==  137) (error "latin small letter z with retroflex hook should be IPA Number 137")

	>> unless (latin_small_letter_c_with_cedilla  ==  138) (error "latin small letter c with cedilla should be IPA Number 138")
	>> unless (latin_small_letter_j_with_crossed_tail  ==  139) (error "latin small letter j with crossed tail should be IPA Number 139")
	>> unless (latin_small_letter_x  ==  140) (error "latin small letter x should be IPA Number 140")
	>> unless (latin_small_letter_gamma  ==  141) (error "latin small letter gamma should be IPA Number 141")
	>> unless (greek_small_letter_chi  ==  142) (error "greek small letter chi should be IPA Number 142")
	>> unless (latin_letter_small_capital_inverted_r  ==  143) (error "latin letter small capital inverted r should be IPA Number 143")
	>> unless (latin_small_letter_h_with_stroke  ==  144) (error "latin small letter h with stroke should be IPA Number 144")
	>> unless (latin_letter_pharyngeal_voiced_fricative  ==  145) (error "latin letter pharyngeal voiced fricative should be IPA Number 145")
	>> unless (latin_small_letter_h  ==  146) (error "latin small letter h should be IPA Number 146")
	>> unless (latin_small_letter_h_with_hook  ==  147) (error "latin small letter h with hook should be IPA Number 147")
	>> unless (latin_small_letter_l_with_belt  ==  148) (error "latin small letter l with belt should be IPA Number 148")
	>> unless (latin_small_letter_lezh  ==  149) (error "latin small letter lezh should be IPA Number 149")
	>> unless (latin_small_letter_v_with_hook  ==  150) (error "latin small letter v with hook should be IPA Number 150")
	>> unless (latin_small_letter_turned_r  ==  151) (error "latin small letter turned r should be IPA Number 151")
	>> unless (latin_small_letter_turned_r_with_hook  ==  152) (error "latin small letter turned r with hook should be IPA Number 152")
	>> unless (latin_small_letter_j  ==  153) (error "latin small letter j should be IPA Number 153")
	>> unless (latin_small_letter_turned_m_with_long_leg  ==  154) (error "latin small letter turned m with long leg should be IPA Number 154")
	>> unless (latin_small_letter_l  ==  155) (error "latin small letter l should be IPA Number 155")
	>> unless (latin_small_letter_l_with_retroflex_hook  ==  156) (error "latin small letter l with retroflex hook should be IPA Number 156")
	>> unless (latin_small_letter_turned_y  ==  157) (error "latin small letter turned y should be IPA Number 157")
	>> unless (latin_letter_small_capital_l  ==  158) (error "latin letter small capital l should be IPA Number 158")
	>> unless (latin_letter_bilabial_click  ==  176) (error "latin letter bilabial click should be IPA Number 176")
	>> unless (latin_letter_dental_click  ==  177) (error "latin letter dental click should be IPA Number 177")
	>> unless (latin_letter_retroflex_click == 178) (error "latin letter retroflex click should be IPA Number 178") -- what is this?
	>> unless (latin_letter_alveolar_click == 179) (error "latin letter alveolar click should be IPA Number 179") -- what is this?
	>> unless (latin_letter_lateral_click  ==  180) (error "latin letter lateral click should be IPA Number 180")
	>> unless (latin_small_letter_b_with_hook  ==  160) (error "latin small letter b with hook should be IPA Number 160")
	>> unless (latin_small_letter_d_with_hook  ==  162) (error "latin small letter d with hook should be IPA Number 162")
	>> unless (latin_small_letter_dotless_j_with_stroke_and_hook  ==  164) (error "latin small letter dotless j with stroke and hook should be IPA Number 164")
	>> unless (latin_small_letter_g_with_hook  ==  166) (error "latin small letter g with hook should be IPA Number 166")
	>> unless (latin_letter_small_capital_g_with_hook  ==  168) (error "latin letter small capital g with hook should be IPA Number 168")
	>> unless (modifier_letter_apostrophe  ==  401) (error "modifier letter apostrophe should be IPA Number 401")
	>> unless (latin_small_letter_i  ==  301) (error "latin small letter i should be IPA Number 301")
	>> unless (latin_small_letter_y  ==  309) (error "latin small letter y should be IPA Number 309")
	>> unless (latin_small_letter_i_with_stroke  ==  317) (error "latin small letter i with stroke should be IPA Number 317")
	>> unless (latin_small_letter_u_bar  ==  318) (error "latin small letter u bar should be IPA Number 318")
	>> unless (latin_small_letter_turned_m  ==  316) (error "latin small letter turned m should be IPA Number 316")
	>> unless (latin_small_letter_u  ==  308) (error "latin small letter u should be IPA Number 308")
	>> unless (latin_letter_small_capital_i  ==  319) (error "latin letter small capital i should be IPA Number 319")
	>> unless (latin_letter_small_capital_y  ==  320) (error "latin letter small capital y should be IPA Number 320")
	>> unless (latin_small_letter_upsilon  ==  321) (error "latin small letter upsilon should be IPA Number 321")
	>> unless (latin_small_letter_e  ==  302) (error "latin small letter e should be IPA Number 302")
	>> unless (latin_small_letter_o_with_stroke  ==  310) (error "latin small letter o with stroke should be IPA Number 310")
	>> unless (latin_small_letter_reversed_e  ==  397) (error "latin small letter reversed e should be IPA Number 397")
	>> unless (latin_small_letter_barred_o  ==  323) (error "latin small letter barred o should be IPA Number 323")
	>> unless (latin_small_letter_rams_horn  ==  315) (error "latin small letter rams horn should be IPA Number 315")
	>> unless (latin_small_letter_o  ==  307) (error "latin small letter o should be IPA Number 307")
	>> unless (latin_small_letter_schwa  ==  322) (error "latin small letter schwa should be IPA Number 322")
	>> unless (latin_small_letter_open_e  ==  303) (error "latin small letter open e should be IPA Number 303")
	>> unless (latin_small_ligature_oe  ==  311) (error "latin small ligature oe should be IPA Number 311")
	>> unless (latin_small_letter_reversed_open_e  ==  326) (error "latin small letter reversed open e should be IPA Number 326")
	>> unless (latin_small_letter_closed_reversed_open_e  ==  395) (error "latin small letter closed reversed open e should be IPA Number 395")
	>> unless (latin_small_letter_turned_v  ==  314) (error "latin small letter turned v should be IPA Number 314")
	>> unless (latin_small_letter_open_o  ==  306) (error "latin small letter open o should be IPA Number 306")
	>> unless (latin_small_letter_ae  ==  325) (error "latin small letter ae should be IPA Number 325")
	>> unless (latin_small_letter_turned_a  ==  324) (error "latin small letter turned a should be IPA Number 324")
	>> unless (latin_small_letter_a  ==  304) (error "latin small letter a should be IPA Number 304")
	>> unless (latin_letter_small_capital_oe  ==  312) (error "latin letter small capital oe should be IPA Number 312")
	>> unless (latin_small_letter_alpha  ==  305) (error "latin small letter alpha should be IPA Number 305")
	>> unless (latin_small_letter_turned_alpha  ==  313) (error "latin small letter turned alpha should be IPA Number 313")
	>> unless (latin_small_letter_turned_w  ==  169) (error "latin small letter turned w should be IPA Number 169")
	>> unless (latin_small_letter_w  ==  170) (error "latin small letter w should be IPA Number 170")
	>> unless (latin_small_letter_turned_h  ==  171) (error "latin small letter turned h should be IPA Number 171")
	>> unless (latin_letter_small_capital_h  ==  172) (error "latin letter small capital h should be IPA Number 172")
	>> unless (latin_letter_reversed_glottal_stop_with_stroke  ==  174) (error "latin letter reversed glottal stop with stroke should be IPA Number 174")
	>> unless (latin_letter_glottal_stop_with_stroke  ==  173) (error "latin letter glottal stop with stroke should be IPA Number 173")
	>> unless (latin_small_letter_c_with_curl  ==  182) (error "latin small letter c with curl should be IPA Number 182")
	>> unless (latin_small_letter_z_with_curl  ==  183) (error "latin small letter z with curl should be IPA Number 183")
	>> unless (latin_small_letter_turned_r_with_long_leg  ==  181) (error "latin small letter turned r with long leg should be IPA Number 181")
	>> unless (latin_small_letter_heng_with_hook  ==  175) (error "latin small letter heng with hook should be IPA Number 175")
	>> unless (combining_double_inverted_breve  ==  433) (error "combining double inverted breve should be IPA Number 433")
	>> unless (combining_double_breve_below  ==  433) (error "combining double breve below should be IPA Number 433")
	>> unless (modifier_letter_vertical_line  ==  501) (error "modifier letter vertical line should be IPA Number 501")
	>> unless (modifier_letter_low_vertical_line  ==  502) (error "modifier letter low vertical line should be IPA Number 502")
	>> unless (modifier_letter_triangular_colon  ==  503) (error "modifier letter triangular colon should be IPA Number 503")
	>> unless (modifier_letter_half_triangular_colon  ==  504) (error "modifier letter half triangular colon should be IPA Number 504")
	>> unless (combining_breve  ==  505) (error "combining breve should be IPA Number 505")
	>> unless (vertical_line  ==  507) (error "vertical line should be IPA Number 507")
	>> unless (double_vertical_line  ==  508) (error "double vertical line should be IPA Number 508")
	>> unless (full_stop  ==  506) (error "full stop should be IPA Number 506")
	>> unless (undertie  ==  509) (error "undertie should be IPA Number 509")
	>> unless (combining_ring_below  ==  402) (error "combining ring (above or below) should be IPA Number 402")

	>> unless (combining_caron_below  ==  403) (error "combining caron below should be IPA Number 403")
	>> unless (modifier_letter_small_h  ==  404) (error "modifier letter small h should be IPA Number 404")
	>> unless (combining_right_half_ring_below  ==  411) (error "combining right half ring below should be IPA Number 411")
	>> unless (combining_left_half_ring_below  ==  412) (error "combining left half ring below should be IPA Number 412")
	>> unless (combining_plus_sign_below  ==  413) (error "combining plus sign below should be IPA Number 413")
	>> unless (combining_minus_sign_below  ==  414) (error "combining minus sign below should be IPA Number 414")
	>> unless (combining_diaeresis  ==  415) (error "combining diaeresis should be IPA Number 415")
	>> unless (combining_x_above  ==  416) (error "combining x above should be IPA Number 416")

	>> unless (combining_vertical_line_above  ==  431) (error "combining vertical line (above or below) should be IPA Number 431")
	>> unless (combining_inverted_breve_below  ==  432) (error "combining inverted breve below should be IPA Number 432")
	>> unless (modifier_letter_rhotic_hook  ==  419) (error "modifier letter rhotic hook should be IPA Number 419")
	>> unless (combining_diaeresis_below  ==  405) (error "combining diaeresis below should be IPA Number 405")
	>> unless (combining_tilde_below  ==  406) (error "combining tilde below should be IPA Number 406")
	>> unless (combining_seagul_below  ==  407) (error "combining seagul below should be IPA Number 407")
	>> unless (modifier_letter_small_w  ==  420) (error "modifier letter small w should be IPA Number 420")
	>> unless (modifier_letter_small_j  ==  421) (error "modifier letter small j should be IPA Number 421")
	>> unless (modifier_letter_small_gamma  ==  422) (error "modifier letter small gamma should be IPA Number 422")
	>> unless (modifier_letter_small_reversed_glottal_stop  ==  423) (error "modifier letter small reversed glottal stop should be IPA Number 423")
	>> unless (combining_tilde_overlay  ==  428) (error "combining tilde overlay should be IPA Number 209")
	>> unless (combining_up_tack_below  ==  429) (error "combining up tack below should be IPA Number 429")
	>> unless (combining_down_tack_below  ==  430) (error "combining down tack below should be IPA Number 430")
	>> unless (combining_left_tack_below  ==  417) (error "combining left tack below should be IPA Number 417")
	>> unless (combining_right_tack_below  ==  418) (error "combining right tack below should be IPA Number 418")
	>> unless (combining_bridge_below  ==  408) (error "combining bridge below should be IPA Number 408")
	>> unless (combining_inverted_bridge_below  ==  409) (error "combining inverted bridge below should be IPA Number 409")
	>> unless (combining_square_below  ==  410) (error "combining square below should be IPA Number 410")
	>> unless (combining_tilde  ==  424) (error "combining tilde should be IPA Number 424")
	>> unless (superscript_latin_small_letter_n  ==  425) (error "superscript latin small letter n should be IPA Number 425")
	>> unless (modifier_letter_small_l  ==  426) (error "modifier letter small l should be IPA Number 426")
	>> unless (combining_left_angle_above  ==  427) (error "combining left angle above should be IPA Number 427")
	>> unless (combining_double_acute_accent  ==  512) (error "combining double acute accent should be IPA Number 512")
	>> unless (combining_acute_accent  ==  513) (error "combining acute accent should be IPA Number 513")
	>> unless (combining_macron  ==  514) (error "combining macron should be IPA Number 514")
	>> unless (combining_grave_accent  ==  515) (error "combining grave accent should be IPA Number 515")
	>> unless (combining_double_grave_accent  ==  516) (error "combining double grave accent should be IPA Number 516")
	>> unless (combining_caron  ==  524) (error "combining caron should be IPA Number 524")
	>> unless (combining_circumflex_accent  ==  525) (error "combining circumflex accent should be IPA Number 525")
	>> unless (combining_macron_acute  ==  526) (error "combining macron acute should be IPA Number 526")
	>> unless (combining_grave_macron  ==  527) (error "combining grave macron should be IPA Number 527")
	>> unless (combining_grave_acute_grave == 528) (error "combining grave acute grave should be IPA Number 528")
	>> unless (north_east_arrow  ==  510) (error "north east arrow should be IPA Number 510")
	>> unless (south_east_arrow  ==  511) (error "south east arrow should be IPA Number 511")
	>> unless (downwards_arrow  ==  517) (error "downwards arrow should be IPA Number 517")
	>> unless (upwards_arrow  ==  518) (error "upwards arrow should be IPA Number 518")
	>> unless (modifier_letter_extra_high_tone_bar  ==  519) (error "modifier letter extra high tone bar should be IPA Number 519")
	>> unless (modifier_letter_high_tone_bar  ==  520) (error "modifier letter high tone bar should be IPA Number 520")
	>> unless (modifier_letter_mid_tone_bar  ==  521) (error "modifier letter mid tone bar should be IPA Number 521")
	>> unless (modifier_letter_low_tone_bar  ==  522) (error "modifier letter low tone bar should be IPA Number 522")
	>> unless (modifier_letter_extra_low_tone_bar  ==  523) (error "modifier letter extra low tone bar should be IPA Number 523");